# Generated by Django 3.2.15 on 2022-08-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Dep_Id', models.IntegerField()),
                ('Salary', models.IntegerField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
